# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.gralaf.service: {{.Values.gralaf.app.lasmServer}}
  name: {{.Values.gralaf.app.lasmServer}}
spec:
  replicas: {{.Values.gralaf.replicas.lasmServer}}
  selector:
    matchLabels:
      org.gralaf.service: {{.Values.gralaf.app.lasmServer}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.gralaf.service: {{.Values.gralaf.app.lasmServer}}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.gralaf.app.lasmServer}}
        image: {{.Values.gralaf.image.lasmServer.repository}}:{{.Values.gralaf.image.lasmServer.tag}}
        imagePullPolicy: {{.Values.gralaf.image.lasmServer.pullPolicy}}
        env:
        - name: SERVICE_HOST
          value: {{.Values.gralaf.app.lasmServer}}
        envFrom:
        - configMapRef:
            name: gralaf-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: configmap
          mountPath: /res   
      {{- if .Values.gralaf.resources.lasmServer.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.gralaf.resources.lasmServer.limits.memory }}
            cpu: {{ .Values.gralaf.resources.lasmServer.limits.cpu }}
          requests:
            memory: {{ .Values.gralaf.resources.lasmServer.requests.memory }}
            cpu: {{ .Values.gralaf.resources.lasmServer.requests.cpu }}
      {{- end}}
      hostname: {{.Values.gralaf.app.lasmServer}}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.gralaf.security.runAsUser }}
        runAsGroup: {{ .Values.gralaf.security.runAsGroup }}
      volumes:
      - name: configmap
        configMap:
          name: lasm-server-configmap
          items:
          - key: configuration.yaml
            path: configuration.yaml
