# Copyright (C) 2022 ZHAW
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.gralaf.service: {{.Values.gralaf.app.lasmServer}}
  name: {{.Values.gralaf.app.lasmServer}}
spec:
  type: NodePort
  ports:
    - name: "http"
      port: {{.Values.gralaf.port.lasmServer}}
      appProtocol: tcp
      nodePort: 32002
  selector:
    org.gralaf.service: {{.Values.gralaf.app.lasmServer}}
status:
  loadBalancer: {}
