# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.gralaf.service: {{.Values.gralaf.app.gralaf}}
  name: {{.Values.gralaf.app.gralaf}}
spec:
  replicas: {{.Values.gralaf.replicas.gralaf}}
  selector:
    matchLabels:
      org.gralaf.service: {{.Values.gralaf.app.gralaf}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.gralaf.service: {{.Values.gralaf.app.gralaf}}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.gralaf.app.gralaf}}
        image: {{.Values.gralaf.image.gralaf.repository}}:{{.Values.gralaf.image.gralaf.tag}}
        imagePullPolicy: {{.Values.gralaf.image.gralaf.pullPolicy}}
        args: [ "--config", "/configs/config.yaml"]
        env:
        - name: SERVICE_HOST
          value: {{.Values.gralaf.app.gralaf}}
        envFrom:
        - configMapRef:
            name: gralaf-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - name: configmap
          mountPath: /configs
        - name: dataset
          mountPath: /dataset
        - name: tmp-dir
          mountPath: /tmp
      {{- if .Values.gralaf.resources.gralaf.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.gralaf.resources.gralaf.limits.memory }}
            cpu: {{ .Values.gralaf.resources.gralaf.limits.cpu }}
          requests:
            memory: {{ .Values.gralaf.resources.gralaf.requests.memory }}
            cpu: {{ .Values.gralaf.resources.gralaf.requests.cpu }}
      {{- end}}
      hostname: {{.Values.gralaf.app.gralaf}}
      restartPolicy: Always
      volumes:
      - name: configmap
        configMap:
          name: gralaf-configmap
          items:
          - key: config.yaml
            path: config.yaml
      - name: dataset
        persistentVolumeClaim:
          claimName: gralaf-dataset
      - name: tmp-dir
        emptyDir: { }
