# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    org.gralaf.service: {{.Values.gralaf.app.mqttClient}}
  name: {{.Values.gralaf.app.mqttClient}}
spec:
  serviceName: "iot-device"
  replicas: {{.Values.gralaf.replicas.mqttClient}}
  selector:
    matchLabels:
      org.gralaf.service: {{.Values.gralaf.app.mqttClient}}
  template:
    metadata:
      labels:
        org.gralaf.service: {{.Values.gralaf.app.mqttClient}}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.gralaf.app.mqttClient}}
        image: {{.Values.gralaf.image.mqttClient.repository}}:{{.Values.gralaf.image.mqttClient.tag}}
        imagePullPolicy: {{.Values.gralaf.image.mqttClient.pullPolicy}}
        args:
        - "-i"
        - {{.Values.gralaf.edgexServer.address}}
        - "-p"
        - {{.Values.gralaf.edgexServer.port}}
        env:
        - name: SERVICE_HOST
          value: {{.Values.gralaf.app.mqttClient}}
        envFrom:
        - configMapRef:
            name: gralaf-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: configmap
          mountPath: /res   
      {{- if .Values.gralaf.resources.mqttClient.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.gralaf.resources.mqttClient.limits.memory }}
            cpu: {{ .Values.gralaf.resources.mqttClient.limits.cpu }}
          requests:
            memory: {{ .Values.gralaf.resources.mqttClient.requests.memory }}
            cpu: {{ .Values.gralaf.resources.mqttClient.requests.cpu }}
      {{- end}}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.gralaf.security.runAsUser }}
        runAsGroup: {{ .Values.gralaf.security.runAsGroup }}
      volumes:
      - name: configmap
        configMap:
          name: mqtt-client-configmap
          items:
          - key: configuration.yaml
            path: configuration.yaml
