# Copyright (C) 2022 ZHAW
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.gralaf.service: {{.Values.gralaf.app.mqttClient}}
  name: {{.Values.gralaf.app.mqttClient}}
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: {{.Values.gralaf.port.mqttClient}}
      appProtocol: tcp
  selector:
    org.gralaf.service: {{.Values.gralaf.app.mqttClient}}
status:
  loadBalancer: {}
