# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.gralaf.service: {{.Values.gralaf.app.loadGenerator}}
  name: {{.Values.gralaf.app.loadGenerator}}
spec:
  replicas: {{.Values.gralaf.replicas.loadGenerator}}
  selector:
    matchLabels:
      org.gralaf.service: {{.Values.gralaf.app.loadGenerator}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.gralaf.service: {{.Values.gralaf.app.loadGenerator}}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{.Values.gralaf.app.loadGenerator}}
        image: {{.Values.gralaf.image.loadGenerator.repository}}:{{.Values.gralaf.image.loadGenerator.tag}}
        imagePullPolicy: {{.Values.gralaf.image.loadGenerator.pullPolicy}}
        args: [ "--target", "http://edgex-ui.edgex.svc.cluster.local:4000","--number_of_users","50", "--number_of_devices","25"]
        env:
        - name: SERVICE_HOST
          value: {{.Values.gralaf.app.loadGenerator}}
        envFrom:
        - configMapRef:
            name: gralaf-common-variables
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: configmap
          mountPath: /res   
      {{- if .Values.gralaf.resources.loadGenerator.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.gralaf.resources.loadGenerator.limits.memory }}
            cpu: {{ .Values.gralaf.resources.loadGenerator.limits.cpu }}
          requests:
            memory: {{ .Values.gralaf.resources.loadGenerator.requests.memory }}
            cpu: {{ .Values.gralaf.resources.loadGenerator.requests.cpu }}
      {{- end}}
      hostname: {{.Values.gralaf.app.loadGenerator}}
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.gralaf.security.runAsUser }}
        runAsGroup: {{ .Values.gralaf.security.runAsGroup }}
      volumes:
      - name: configmap
        configMap:
          name: load-generator-configmap
          items:
          - key: configuration.yaml
            path: configuration.yaml
