# Copyright (C) 2022 ZHAW
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  labels:
    org.gralaf.service: {{.Values.gralaf.app.gralaf}}
  name: {{.Values.gralaf.app.gralaf}}
spec:
  type: NodePort
  ports:
    - name: "http"
      port: {{.Values.gralaf.port.gralaf}}
      appProtocol: tcp
      nodePort: 32001
  selector:
    org.gralaf.service: {{.Values.gralaf.app.gralaf}}
status:
  loadBalancer: {}
